// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg6L2W0-uEnxaVKadwQDajZE9pVnETpY0',
    appId: '1:256391070321:web:1f9c0af68befc1474111d0',
    messagingSenderId: '256391070321',
    projectId: 'catalogo-peliculas-928f2',
    authDomain: 'catalogo-peliculas-928f2.firebaseapp.com',
    storageBucket: 'catalogo-peliculas-928f2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6MxJ3NPnKiHIuFLAFeJGpGhCe3hzr038',
    appId: '1:256391070321:android:6dc1d478573359094111d0',
    messagingSenderId: '256391070321',
    projectId: 'catalogo-peliculas-928f2',
    storageBucket: 'catalogo-peliculas-928f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwcrRBm1rRuCrqfhvJzhf6PUNyrqSiCx0',
    appId: '1:256391070321:ios:fe25aa153d49f7914111d0',
    messagingSenderId: '256391070321',
    projectId: 'catalogo-peliculas-928f2',
    storageBucket: 'catalogo-peliculas-928f2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwcrRBm1rRuCrqfhvJzhf6PUNyrqSiCx0',
    appId: '1:256391070321:ios:fe25aa153d49f7914111d0',
    messagingSenderId: '256391070321',
    projectId: 'catalogo-peliculas-928f2',
    storageBucket: 'catalogo-peliculas-928f2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg6L2W0-uEnxaVKadwQDajZE9pVnETpY0',
    appId: '1:256391070321:web:38b7ab066c02ecdb4111d0',
    messagingSenderId: '256391070321',
    projectId: 'catalogo-peliculas-928f2',
    authDomain: 'catalogo-peliculas-928f2.firebaseapp.com',
    storageBucket: 'catalogo-peliculas-928f2.firebasestorage.app',
  );
}
